CREATE TABLE BD_LAB.ABITURIENTS (
  ID            NUMBER            NOT NULL,
  NAME          VARCHAR2(20 BYTE) NOT NULL,
  SURNAME       VARCHAR2(30 BYTE) NOT NULL,
  MIDLE_NAME    VARCHAR2(20 BYTE) NOT NULL,
  SEX           VARCHAR2(6 BYTE)  NOT NULL,
  BIRTHDAY      DATE              NOT NULL,
  SPECIALITY_ID NUMBER,
  SCORE_ID      NUMBER,
  CONSTRAINT XPKABITURIENTS PRIMARY KEY (ID) USING INDEX TABLESPACE USERS STORAGE (INITIAL 64 K
                                                                                   NEXT 1 M
                                                                                   MAXEXTENTS UNLIMITED),
  CONSTRAINT R_3 FOREIGN KEY (SPECIALITY_ID)
  REFERENCES BD_LAB.SPECIALTIES (SPECIALITY_ID) ON DELETE SET NULL,
  CONSTRAINT R_5 FOREIGN KEY (SCORE_ID)
  REFERENCES BD_LAB.RAITING (SCORE_ID) ON DELETE SET NULL
)
TABLESPACE USERS
LOGGING;