


INSERT INTO ABITURIENTS(
  NAME, SURNAME, MIDLE_NAME, SEX, BIRTHDAY, ABITURIENT_ID
)
VALUES ('VOVA', 'PUTIN', 'VLADIMIROVYCH', 'MALE', TO_DATE('02 3,85','MM DD,YY'), 001);INSERT INTO ABITURIENTS(
  NAME, SURNAME, MIDLE_NAME, SEX, BIRTHDAY, ABITURIENT_ID
  )
VALUES ('DIMA', 'MEDVED', 'ANATOLICH', 'MALE', TO_DATE('01 10,90','MM DD, YY'),002);INSERT INTO ABITURIENTS(
  NAME, SURNAME, MIDLE_NAME, SEX, BIRTHDAY, ABITURIENT_ID
)
VALUES ('PETYA', 'PETROV', 'DMITRICH', 'MALE', TO_DATE('04 18,78','MM DD, YY'), 003);INSERT INTO ABITURIENTS(
  NAME, SURNAME, MIDLE_NAME, SEX, BIRTHDAY, ABITURIENT_ID
)
VALUES ('IVAN', 'PUTIN', 'IVANYCH', 'MALE', TO_DATE('01 25,98','MM DD, YY'), 004);INSERT INTO ABITURIENTS(
  NAME, SURNAME, MIDLE_NAME, SEX, BIRTHDAY, ABITURIENT_ID
)
VALUES ('VASYA', 'IVANOV', 'VLADIMIROVYCH', 'MALE', TO_DATE('10 5,92','MM DD, YY'), 005);INSERT INTO ABITURIENTS(
  NAME, SURNAME, MIDLE_NAME, SEX, BIRTHDAY, ABITURIENT_ID
)
VALUES ('MASHA', 'VOLKOVA', 'IVANOVNA', 'FEMALE', TO_DATE('05 9,84','MM DD, YY'), 006);INSERT INTO ABITURIENTS(
  NAME, SURNAME, MIDLE_NAME, SEX, BIRTHDAY, ABITURIENT_ID
)
VALUES ('NINA', 'TURKINA', 'VLADIMIROVNA', 'FEMALE', TO_DATE('08 7,91','MM DD, YY'), 007);INSERT INTO ABITURIENTS(
  NAME, SURNAME, MIDLE_NAME, SEX, BIRTHDAY, ABITURIENT_ID
)
VALUES ('IZABELA', 'BUSH', 'PETROVNA', 'FEMALE', TO_DATE('11 1,90','MM DD, YY'), 008);INSERT INTO ABITURIENTS(
  NAME, SURNAME, MIDLE_NAME, SEX, BIRTHDAY, ABITURIENT_ID
)
VALUES ('VOVKA', 'PUTINKA', 'VLADIMIROVYCH', 'MALE', TO_DATE('12 3,97','MM DD, YY'), 009);INSERT INTO ABITURIENTS(
  NAME, SURNAME, MIDLE_NAME, SEX, BIRTHDAY, ABITURIENT_ID
)
VALUES ('KRIS', 'KROTOV', 'MIHALYCH', 'MALE', TO_DATE('07 20,70','MM DD, YY'), 010);