INSERT INTO STATEMENT(
  STATEMENT_ID, SPECIALITY_ID, EXAM_ID, ABITURIENT_ID
)
VALUES (1, 2, 3, 001);
INSERT INTO STATEMENT(
  STATEMENT_ID, SPECIALITY_ID, EXAM_ID, ABITURIENT_ID
)
VALUES (2, 5, 1, 002);
INSERT INTO STATEMENT(
  STATEMENT_ID, SPECIALITY_ID, EXAM_ID, ABITURIENT_ID
)
VALUES (3, 3, 5, 003);
INSERT INTO STATEMENT(
  STATEMENT_ID, SPECIALITY_ID, EXAM_ID, ABITURIENT_ID
)
VALUES (4, 1, 2, 004);
INSERT INTO STATEMENT(
  STATEMENT_ID, SPECIALITY_ID, EXAM_ID, ABITURIENT_ID
)
VALUES (5, 9, 8, 005);
INSERT INTO STATEMENT(
  STATEMENT_ID, SPECIALITY_ID, EXAM_ID, ABITURIENT_ID
)
VALUES (6, 7, 10, 006);
INSERT INTO STATEMENT(
  STATEMENT_ID, SPECIALITY_ID, EXAM_ID, ABITURIENT_ID
)
VALUES (7, 4, 9, 007);
INSERT INTO STATEMENT(
  STATEMENT_ID, SPECIALITY_ID, EXAM_ID, ABITURIENT_ID
)
VALUES (8, 6, 6, 008);
INSERT INTO STATEMENT(
  STATEMENT_ID, SPECIALITY_ID, EXAM_ID, ABITURIENT_ID
)
VALUES (9, 8, 7, 009);
INSERT INTO STATEMENT(
  STATEMENT_ID, SPECIALITY_ID, EXAM_ID, ABITURIENT_ID
)
VALUES (10, 10, 4, 010);