INSERT INTO SPECIALITY_OBJECT(
  SPECIALITY_ID, OBJECT_ID
)
VALUES (1, 5);
INSERT INTO SPECIALITY_OBJECT(
  SPECIALITY_ID, OBJECT_ID
)
VALUES (2, 4);
INSERT INTO SPECIALITY_OBJECT(
  SPECIALITY_ID, OBJECT_ID
)
VALUES (3, 9);
INSERT INTO SPECIALITY_OBJECT(
  SPECIALITY_ID, OBJECT_ID
)
VALUES (3, 5);
INSERT INTO SPECIALITY_OBJECT(
  SPECIALITY_ID, OBJECT_ID
)
VALUES (8, 6);
INSERT INTO SPECIALITY_OBJECT(
  SPECIALITY_ID, OBJECT_ID
)
VALUES (7, 6);

INSERT INTO SPECIALITY_OBJECT(
  SPECIALITY_ID, OBJECT_ID
)
VALUES (9, 5);
INSERT INTO SPECIALITY_OBJECT(
  SPECIALITY_ID, OBJECT_ID
)
VALUES (2, 10);
INSERT INTO SPECIALITY_OBJECT(
  SPECIALITY_ID, OBJECT_ID
)
VALUES (4, 7);
INSERT INTO SPECIALITY_OBJECT(
  SPECIALITY_ID, OBJECT_ID
)
VALUES (1, 7);
INSERT INTO SPECIALITY_OBJECT(
  SPECIALITY_ID, OBJECT_ID
)
VALUES (4, 2);
INSERT INTO SPECIALITY_OBJECT(
  SPECIALITY_ID, OBJECT_ID
)
VALUES (3, 7);
INSERT INTO SPECIALITY_OBJECT(
  SPECIALITY_ID, OBJECT_ID
)
VALUES (6, 8);
INSERT INTO SPECIALITY_OBJECT(
  SPECIALITY_ID, OBJECT_ID
)
VALUES (8, 1);
INSERT INTO SPECIALITY_OBJECT(
  SPECIALITY_ID, OBJECT_ID
)
VALUES (4, 3);
INSERT INTO SPECIALITY_OBJECT(
  SPECIALITY_ID, OBJECT_ID
)
VALUES (2, 2);
INSERT INTO SPECIALITY_OBJECT(
  SPECIALITY_ID, OBJECT_ID
)
VALUES (7, 1);
INSERT INTO SPECIALITY_OBJECT(
  SPECIALITY_ID, OBJECT_ID
)
VALUES (5, 2);
INSERT INTO SPECIALITY_OBJECT(
  SPECIALITY_ID, OBJECT_ID
)
VALUES (10, 4);
INSERT INTO SPECIALITY_OBJECT(
  SPECIALITY_ID, OBJECT_ID
)
VALUES (6, 3);
INSERT INTO SPECIALITY_OBJECT(
  SPECIALITY_ID, OBJECT_ID
)
VALUES (7, 2);
INSERT INTO SPECIALITY_OBJECT(
  SPECIALITY_ID, OBJECT_ID
)
VALUES (8, 2);

