INSERT INTO OBJECTS(
  OBJECT_NAME
)
VALUES ('MATH');
INSERT INTO OBJECTS(
  OBJECT_NAME
)
VALUES ('PHYSICS' );
INSERT INTO OBJECTS(
  OBJECT_NAME
)
VALUES ('ENGLISH' );
INSERT INTO OBJECTS(
  OBJECT_NAME
)
VALUES ('COMPUTER_SCIENCE' );
INSERT INTO OBJECTS(
  OBJECT_NAME
)
VALUES ('PHILOSOPHY');
INSERT INTO OBJECTS(
  OBJECT_NAME
)
VALUES ('HYSTORY');
INSERT INTO OBJECTS(
  OBJECT_NAME
)
VALUES ('MATH_LOGIC');
INSERT INTO OBJECTS(
  OBJECT_NAME
)
VALUES ('BIOLOGY');
INSERT INTO OBJECTS(
  OBJECT_NAME
)
VALUES ('CHEMISTRY');
INSERT INTO OBJECTS(
  OBJECT_NAME
)
VALUES ('SOCIOLOGY');