
INSERT INTO RAITING(
  SCORE_ID, IS_MISSING_EXAM
)
VALUES (1, NULL);

INSERT INTO RAITING(
  SCORE_ID, IS_MISSING_EXAM
)
VALUES (2, NULL);

INSERT INTO RAITING(
  SCORE_ID, IS_MISSING_EXAM
)
VALUES (3, NULL);

INSERT INTO RAITING(
  SCORE_ID, IS_MISSING_EXAM
)
VALUES (4, NULL);

INSERT INTO RAITING(
  SCORE_ID, IS_MISSING_EXAM
)
VALUES (5, 'YES');

INSERT INTO RAITING(
  SCORE_ID, IS_MISSING_EXAM
)
VALUES (6, NULL);

INSERT INTO RAITING(
  SCORE_ID, IS_MISSING_EXAM
)
VALUES (7, NULL);

INSERT INTO RAITING(
  SCORE_ID, IS_MISSING_EXAM
)
VALUES (8, 'YES');

INSERT INTO RAITING(
  SCORE_ID, IS_MISSING_EXAM
)
VALUES (9, NULL);

INSERT INTO RAITING(
  SCORE_ID, IS_MISSING_EXAM
)
VALUES (10, 'YES');