INSERT INTO SPECIALTIES(
  SPECIALITY_ID,NAME
)
VALUES (1,'FIIT');
INSERT INTO SPECIALTIES(
  SPECIALITY_ID,NAME
)
VALUES (2,'PMI');
INSERT INTO SPECIALTIES(
  SPECIALITY_ID,NAME
)
VALUES (3,'IWT');
INSERT INTO SPECIALTIES(
  SPECIALITY_ID, NAME
)
VALUES (4,'IBAS');
INSERT INTO SPECIALTIES(
  SPECIALITY_ID, NAME
)
VALUES (5,'PMF');
INSERT INTO SPECIALTIES(
  SPECIALITY_ID,NAME
)
VALUES (6,'BS');
INSERT INTO SPECIALTIES(
  SPECIALITY_ID,NAME
)
VALUES (7,'GS');
INSERT INTO SPECIALTIES(
  SPECIALITY_ID, NAME
)
VALUES (8,'KRT');
INSERT INTO SPECIALTIES(
  SPECIALITY_ID,NAME
)
VALUES (9,'PRES');
INSERT INTO SPECIALTIES(
  SPECIALITY_ID,NAME
)
VALUES (10,'RGB');