INSERT INTO OBJECT_REITINGS(
  SCORE_ID, OBJECT_NAME, MARK
)
VALUES (1, 'MATH', 96);

INSERT INTO OBJECT_REITINGS(
  SCORE_ID, OBJECT_NAME, MARK
)
VALUES (3, 'ENGLISH', 32);

INSERT INTO OBJECT_REITINGS(
  SCORE_ID, OBJECT_NAME, MARK
)
VALUES (6, 'BIOLOGY', 74);

INSERT INTO OBJECT_REITINGS(
  SCORE_ID, OBJECT_NAME, MARK
)
VALUES (6, 'CHEMISTRY', 89);

INSERT INTO OBJECT_REITINGS(
  SCORE_ID, OBJECT_NAME, MARK
)
VALUES (9, 'SOCIOLOGY', 29);

INSERT INTO OBJECT_REITINGS(
  SCORE_ID, OBJECT_NAME, MARK
)
VALUES (2, 'HYSTORY', 74);

INSERT INTO OBJECT_REITINGS(
  SCORE_ID, OBJECT_NAME, MARK
)
VALUES (4, 'PHYSICS', 104);

INSERT INTO OBJECT_REITINGS(
  SCORE_ID, OBJECT_NAME, MARK
)
VALUES (8, 'MATH_LOGIC', 84);

INSERT INTO OBJECT_REITINGS(
  SCORE_ID, OBJECT_NAME, MARK
)
VALUES (9, 'ENGLISH', 93);

INSERT INTO OBJECT_REITINGS(
  SCORE_ID, OBJECT_NAME, MARK
)
VALUES (3, 'PHILOSOPHY', 97);