INSERT INTO EXAM(
  EXAM_ID, PRESENCE
)
VALUES (1, 'YES');
INSERT INTO EXAM(
  EXAM_ID, PRESENCE
)
VALUES (2, 'NO');
INSERT INTO EXAM(
  EXAM_ID, PRESENCE
)
VALUES (3, 'YES');
INSERT INTO EXAM(
  EXAM_ID, PRESENCE
)
VALUES (4, 'YES');
INSERT INTO EXAM(
  EXAM_ID, PRESENCE
)
VALUES (5, 'YES');
INSERT INTO EXAM(
  EXAM_ID, PRESENCE
)
VALUES (6, 'NO');
INSERT INTO EXAM(
  EXAM_ID, PRESENCE
)
VALUES (7, 'NO');
INSERT INTO EXAM(
  EXAM_ID, PRESENCE
)
VALUES (8, 'YES');
INSERT INTO EXAM(
  EXAM_ID, PRESENCE
)
VALUES (9, 'YES');
INSERT INTO EXAM(
  EXAM_ID, PRESENCE
)
VALUES (10, 'NO');