INSERT INTO OBJECT_RAITING(
  MARK, EXAM_ID, OBJECT_ID, OBJECT_RAITING_ID
)
VALUES (5, 1, 3, 1);
INSERT INTO OBJECT_RAITING(
  MARK, EXAM_ID, OBJECT_ID, OBJECT_RAITING_ID
)
VALUES (3, 1, 8, 2);
INSERT INTO OBJECT_RAITING(
  MARK, EXAM_ID, OBJECT_ID, OBJECT_RAITING_ID
)
VALUES (4, 3, 5, 3);
INSERT INTO OBJECT_RAITING(
  MARK, EXAM_ID, OBJECT_ID, OBJECT_RAITING_ID
)
VALUES (2, 4, 7, 4);
INSERT INTO OBJECT_RAITING(
  MARK, EXAM_ID, OBJECT_ID, OBJECT_RAITING_ID
)
VALUES (5, 5, 3, 5);
INSERT INTO OBJECT_RAITING(
  MARK, EXAM_ID, OBJECT_ID, OBJECT_RAITING_ID
)
VALUES (2, 5, 4, 6);
INSERT INTO OBJECT_RAITING(
  MARK, EXAM_ID, OBJECT_ID, OBJECT_RAITING_ID
)
VALUES (3, 8, 6, 7);
INSERT INTO OBJECT_RAITING(
  MARK, EXAM_ID, OBJECT_ID, OBJECT_RAITING_ID
)
VALUES (5, 8, 1, 8);
INSERT INTO OBJECT_RAITING(
  MARK, EXAM_ID, OBJECT_ID, OBJECT_RAITING_ID
)
VALUES (4, 9, 2, 9);
INSERT INTO OBJECT_RAITING(
  MARK, EXAM_ID, OBJECT_ID, OBJECT_RAITING_ID
)
VALUES (2, 8, 5, 10);
