
INSERT INTO OBJECTS(
  OBJECT_NAME,OBJECT_ID
)
VALUES ('MATH',1);
INSERT INTO OBJECTS(
  OBJECT_NAME,OBJECT_ID
)
VALUES ('PHYSICS',2 );
INSERT INTO OBJECTS(
  OBJECT_NAME,OBJECT_ID
)
VALUES ('ENGLISH',3 );
INSERT INTO OBJECTS(
  OBJECT_NAME,OBJECT_ID
)
VALUES ('COMPUTER_SCIENCE',4 );
INSERT INTO OBJECTS(
  OBJECT_NAME,OBJECT_ID
)
VALUES ('PHILOSOPHY',5);
INSERT INTO OBJECTS(
  OBJECT_NAME,OBJECT_ID
)
VALUES ('HYSTORY',6);
INSERT INTO OBJECTS(
  OBJECT_NAME,OBJECT_ID
)
VALUES ('MATH_LOGIC',7);
INSERT INTO OBJECTS(
  OBJECT_NAME,OBJECT_ID
)
VALUES ('BIOLOGY',8);
INSERT INTO OBJECTS(
  OBJECT_NAME,OBJECT_ID
)
VALUES ('CHEMISTRY',9);
INSERT INTO OBJECTS(
  OBJECT_NAME,OBJECT_ID
)
VALUES ('SOCIOLOGY',10);